### ISSUE TITLE
Web version webVersion: '2.2413.51' type remote is not working anymore 

### ISSUE THREAD

**Issue by foodcodechat** [wppconnect-team/wa-version#612]
Hello everyone please i need help 
i was using this version but now it's not working anymore please i need help : 

    webVersion: '2.2413.51',
    webVersionCache: {
       type: "remote",
       remotePath:
         "https://mycloudvps.ma/uploads/whatsapp.html", // my server 
     },

**Comment by ArturKhasa** [comment]
same problem, please help

**Comment by tegarferdigantara** [comment]
same here,
I was used latest version of webVersion 2.3000.1014580163-alpha but still error
![image](https://github.com/wppconnect-team/wa-version/assets/115655820/0416aede-f2a6-480c-88d9-1dbd0512fc97)

![image](https://github.com/wppconnect-team/wa-version/assets/115655820/0e503765-8c67-456e-b76b-499ede45413b)

**Comment by foodcodechat** [comment]
hello @tegarferdigantara it was working for you these last days ?
or it's your first time using it  ?

**Comment by abdelazizElemary** [comment]
it was working until 8 hours ago. Check their latest commit they remove all the beta versions. And no any alpha version working

**Comment by tegarferdigantara** [comment]
> it was working until 8 hours ago. Check their latest commit they remove all the beta versions. And no any alpha version working

ahh I see 
![image](https://github.com/wppconnect-team/wa-version/assets/115655820/25d6269f-4dd0-418a-b184-1fe24a515110)

**Comment by ArturKhasa** [comment]
> > it was working until 8 hours ago. Check their latest commit they remove all the beta versions. And no any alpha version working
> 
> ahh I see ![image](https://private-user-images.githubusercontent.com/115655820/344588559-25d6269f-4dd0-418a-b184-1fe24a515110.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MjA1OTYsIm5iZiI6MTcxOTgyMDI5NiwicGF0aCI6Ii8xMTU2NTU4MjAvMzQ0NTg4NTU5LTI1ZDYyNjlmLTRkZDAtNDE4YS1iMTg0LTFmZTI0YTUxNTExMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQwNzUxMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjYwNjdmOTQ5ZGFjOWVjOTJhM2Y1ZDBmZmQwZmQzMjMzOTY4NGJkNTYwZjdmMzkwMTQ1OWY5YzhiNTg1OGFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TvnBTTfcwa55RpOeFRDRzCGArkJ4DKlj131V4B-17kc)

This versions is not working too. I can't catch active event, when phone was scaned

**Comment by foodcodechat** [comment]
[
![344588559-25d6269f-4dd0-418a-b184-1fe24a515110](https://github.com/wppconnect-team/wa-version/assets/174304271/c24947f0-6a70-4fe2-983c-5827af027c5d)
](url)


yeah but at least this version keep generating a loop of qr code so it's a little bit close .... the other beta version is not working anymore i have a backup of it but it's not working it generate only 1 qr and it stop working

**Comment by tegarferdigantara** [comment]
> [ ![344588559-25d6269f-4dd0-418a-b184-1fe24a515110](https://private-user-images.githubusercontent.com/174304271/344589790-c24947f0-6a70-4fe2-983c-5827af027c5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MjA4MDcsIm5iZiI6MTcxOTgyMDUwNywicGF0aCI6Ii8xNzQzMDQyNzEvMzQ0NTg5NzkwLWMyNDk0N2YwLTZhNzAtNGZlMi05ODNjLTU4MjdhZjAyN2M1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQwNzU1MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODE4YTA5YzViMjNjNmU2NjA3NTgwZWExNmEwMjIyZDlhYzg4N2RmY2UwZGE0YTc3YWI3M2Y3MTVjMzZhNjkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Q71By4nEhOOLY9D-LbtVtkRNfyTFg4cBUCrgH1BhuhA) ](url)
> 
> yeah but at least this version keep generating a loop of qr code so it's a little bit close .... the other beta version is not working anymore i have a backup of it but it's not working it generate only 1 qr and it stop working

yeah, hopefully the beta release will be updated quickly xD

**Comment by ArturKhasa** [comment]
how long should wait?

**Comment by ArsalT** [comment]
The same issue, I have tried many versions but none is working. The previous versions I was using are removed and have tried running their given code but no progress. Does anyone has any idea of the issue? And is there any alternative to it?

**Comment by rizkihermansyah83** [comment]
same probles.. please helpme sir...
thanks...

**Comment by YairEtzion** [comment]
I have the same issue, no other versions work.

**Comment by Obaadz** [comment]
Same issue, waiting update...

**Comment by asbogrek** [comment]
Same issue, and other versions aren't working either. I'm waiting for an update

**Comment by palbano30** [comment]
Mesmo problema aqui.

**Comment by bibibang-dotcom** [comment]
Same issue, help plz

**Comment by longgtruong** [comment]
same issue

**Comment by Andrauss** [comment]
Same issue, no working versions

**Comment by ashern000** [comment]
Same issue, no working versions and broke my apps

**Comment by claudioluispazos** [comment]
I see that 2.2413.51-beta was it removed from this repository. Can you revert that commit, please?

**Comment by JdAkram25514** [comment]
Any alternative solution?

**Comment by MOHDaazam** [comment]
One latest Alpha version was added

https://github.com/wppconnect-team/wa-version/commit/bd46ca03c765648e9ce0f788670a788953d63fd8#diff-2d5b12f9201834fecbafa944b5976c5153e286459c474b496d9db28f1733a5f4

I tried by giving the URL , single session and even multiple session
```
remotePath:
        "https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.3000.1014590669-alpha.html",
```
 It throws below error after QR scan
```
 
         throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
              ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')
    at pptr://__puppeteer_evaluation_script__:5:95
```

**Comment by abdelazizElemary** [comment]
> One latest Alpha version was added
> 
> [bd46ca0#diff-2d5b12f9201834fecbafa944b5976c5153e286459c474b496d9db28f1733a5f4](https://github.com/wppconnect-team/wa-version/commit/bd46ca03c765648e9ce0f788670a788953d63fd8#diff-2d5b12f9201834fecbafa944b5976c5153e286459c474b496d9db28f1733a5f4)
> 
> I tried by giving the URL , single session and even multiple session
> 
> ```
> remotePath:
>         "https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.3000.1014590669-alpha.html",
> ```
> 
> It throws below error after QR scan
> 
> ```
>  
>          throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
>               ^
> 
> Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')
>     at pptr://__puppeteer_evaluation_script__:5:95
> ```

same issue happened to me when trying the new added a file

**Comment by ArturKhasa** [comment]
> > One latest Alpha version was added
> > [bd46ca0#diff-2d5b12f9201834fecbafa944b5976c5153e286459c474b496d9db28f1733a5f4](https://github.com/wppconnect-team/wa-version/commit/bd46ca03c765648e9ce0f788670a788953d63fd8#diff-2d5b12f9201834fecbafa944b5976c5153e286459c474b496d9db28f1733a5f4)
> > I tried by giving the URL , single session and even multiple session
> > ```
> > remotePath:
> >         "https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.3000.1014590669-alpha.html",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It throws below error after QR scan
> > ```
> >  
> >          throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
> >               ^
> > 
> > Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')
> >     at pptr://__puppeteer_evaluation_script__:5:95
> > ```
> 
> same issue happened to me when trying the new added a file

Try it too. Same problem

**Comment by llcoletti** [comment]
Same problem

**Comment by abdelazizElemary** [comment]
Please if you got the answer add it here Thanks 

https://stackoverflow.com/questions/78692742/whatsapp-web-js-package-failing-when-scanning-the-qr-code

**Comment by foodcodechat** [comment]
I just saw the latest alpha version added 1 hour ago >>>>  2.3000.1014590669-alpha.html

it is correct to test it this way after uploading it on my server >>> 
like that ? :

webVersion: '2.3000.1014590669',
webVersionCache: {
   type: "remote",
   remotePath:
     "https://mycloudvps.ma/uploads/2.3000.1014590669-alpha.html.html", // my server 
 },

**Comment by CauaCodeDev** [comment]
Remove webVersionCache do codigo e use execute:

npm install github:pedroslopez/whatsapp-web.js#webpack-exodus

irá resolver o problema

**Comment by foodcodechat** [comment]
> Remove webVersionCache do codigo e use execute:
> 
> npm install github:pedroslopez/whatsapp-web.js#webpack-exodus
> 
> irá resolver o problema

PLease can you show an example how to use codigo ?

**Comment by CauaCodeDev** [comment]
> > Remova webVersionCache do código e use execute:
> > npm instalar github:pedroslopez/whatsapp-web.js#webpack-exodus
> > irá resolver o problema
> 
> Por favor, você pode mostrar um exemplo de como usar o codigo?

Execute no terminal, eu uso ubuntu 18 e executei esse comando abaixo e resolvo.

npm instalar github:pedroslopez/whatsapp-web.js#webpack-exodus

const client = new Client({
authStrategy: new LocalAuth(),
puppeteer: {
args: [
'--no-sandbox',
'--disable-setuid-sandbox',
'--disable-accelerated-2d-canvas',
'--no-first-run',
'--no-zygote',
'--disable-gpu'
],
},
});

**Comment by foodcodechat** [comment]
ok i'm trying thank you so much

**Comment by CauaCodeDev** [comment]
> ok, estou tentando, muito obrigado

resolveu ?

**Comment by abdelazizElemary** [comment]
Someone posted an answer here and I tried and it worked!

https://stackoverflow.com/questions/78692742/whatsapp-web-js-package-failing-when-scanning-the-qr-code/78692943#78692943

**Comment by ramonfontes** [comment]
> npm install github:pedroslopez/whatsapp-web.js#webpack-exodus

I confirm that this works

**Comment by palbano30** [comment]
Não deu certo para mim.

**Comment by foodcodechat** [comment]
> Não deu certo para mim.

give us more detail about your code and the structure of your whatsapp project

**Comment by proggerkz** [comment]
for me its also not worked, i cant even scan the code it says
It is not possible to link new devices

**Comment by foodcodechat** [comment]
try to logout all the whsatapp web session of your  device >>>> in connected devices and try again

**Comment by proggerkz** [comment]
@foodcodechat tried it still not helped

**Comment by lanstat** [comment]
> Thank you CauaCodeDev and abdelazizElemary 👍
> 
> first delete package.json and package-lock.json 2- install the module witht his commande line >>>> npm install github:pedroslopez/whatsapp-web.js#webpack-exodus 3- add the code below :
> 
> // you should require whatsapp-web.js and not the "./index" const { Client, Location, Poll, List, Buttons, LocalAuth } = require('whatsapp-web.js');
> 
> const client = new Client({ authStrategy: new LocalAuth({ clientId: this.id, dataPath: this.sessionPath, }), // proxyAuthentication: { username: 'username', password: 'password' }, puppeteer: { // args: ['--proxy-server=proxy-server-that-requires-authentication.example.com'], args: ['--no-sandbox', '--disable-setuid-sandbox'] , headless: true }, });

Thanks! It works for me.

This is my client instantiation.
Also I unbinded all my linked devices.

```
const client = new Client({
        webVersion: '2.3000.1014590669',
        webVersionCache: {
                type: 'remote',
                remotePath: 'https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.3000.1014590669-alpha.html'
        },
        puppeteer: {
                headless: true,
                args: [
                        '--no-sandbox',
                        '--disable-setuid-sandbox',
                        '--disable-dev-shm-usage',
                        '--disable-accelerated-2d-canvas',
                        '--disable-gpu',
                        '--single-process',
                        '--no-zygote'
                ],
        }
});
```

**Comment by palbano30** [comment]
Em qual arquivo devo fazer essa elteração? @lanstat

**Comment by palbano30** [comment]
Constants.js?

**Comment by orl4nd1** [comment]
> Thank you CauaCodeDev and abdelazizElemary 👍
> 
> first delete package.json and package-lock.json 2- install the module witht his commande line >>>> npm install github:pedroslopez/whatsapp-web.js#webpack-exodus 3- add the code below :
> 
> // you should require whatsapp-web.js and not the "./index" const { Client, Location, Poll, List, Buttons, LocalAuth } = require('whatsapp-web.js');
> 
> const client = new Client({ authStrategy: new LocalAuth({ clientId: this.id, dataPath: this.sessionPath, }), // proxyAuthentication: { username: 'username', password: 'password' }, puppeteer: { // args: ['--proxy-server=proxy-server-that-requires-authentication.example.com'], args: ['--no-sandbox', '--disable-setuid-sandbox'] , headless: true }, });

the goat.

**Comment by llcoletti** [comment]
> Remove webVersionCache do codigo e use execute:
> 
> npm install github:pedroslopez/whatsapp-web.js#webpack-exodus
> 
> irá resolver o problema


Thank you, that worked for me

**Comment by abdelazizElemary** [comment]
> possible

Check this out

https://stackoverflow.com/questions/78692742/whatsapp-web-js-package-failing-when-scanning-the-qr-code

If you are using yarn you will need to tweak the add command a little bit. Delete node_modules and any old sessions and from the client initialization in your code remove webVersionCache part only puppeteer flags and you auth part as in the stackoverflow link. I hope it works 🙌

**Comment by palbano30** [comment]
Aqui ainda não deu certo, o que vai ser alterado em qual arquivo.

**Comment by palbano30** [comment]
1 Jul 16:37:50 - [error] Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')
    at __puppeteer_evaluation_script__:5:95
    at ExecutionContext._evaluateInternal (C:\Users\serverlocal\.node-red\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (C:\Users\serverlocal\.node-red\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async Client.initialize (C:\Users\serverlocal\.node-red\node_modules\whatsapp-web.js\src\Client.js:323:9)
PS C:\Users\serverlocal\.node-red>

**Comment by sagirr** [comment]
npm install github:pedroslopez/whatsapp-web.js#webpack-exodus
this solved my problem thanks

**Comment by reinforcers** [comment]
all I did was `npm install github:pedroslopez/whatsapp-web.js#webpack-exodus`  without removing `package.json` and then remove the `webVersionCache` and its working again

**Comment by MOHDaazam** [comment]
https://stackoverflow.com/questions/78692742/whatsapp-web-js-package-failing-when-scanning-the-qr-code/78692943#78692943

I tried this solution and it's working as intended.

**Comment by MOHDaazam** [comment]
By the way Guys, Where do you deploy your services (of whatsapp-js), I tried with render.com and netlify, but nothing works out!

**Comment by yairmelamed** [comment]
me too.. please help..

**Comment by sagirr** [comment]
I have special vindows vds. You can take a vds for this

2 Tem 2024 Sal 07:14 tarihinde Mohd Azam ***@***.***> şunu
yazdı:

**Comment by MOHDaazam** [comment]
@mrameen 

You can follow these steps 
https://stackoverflow.com/questions/78692742/whatsapp-web-js-package-failing-when-scanning-the-qr-code/78692943#78692943

then you don't need to mention `webVersionCache`  and even `webVersion` it will creates it own, during runtime.

**Comment by rizkihermansyah83** [comment]
> @mrameen
> 
> You can follow these steps https://stackoverflow.com/questions/78692742/whatsapp-web-js-package-failing-when-scanning-the-qr-code/78692943#78692943
> 
> then you don't need to mention `webVersionCache` and even `webVersion` it will creates it own, during runtime.

i have do this in node-red,, but still error,, can you explain more please...

**Comment by MOHDaazam** [comment]
@rizkihermansyah83 Did you tried deleting the previous cache, like .web_auth, before restarting ?
And make sure you have delete the  current whatsapp-web.js from package.json and delete the node_module then install this

`npm install github:pedroslopez/whatsapp-web.js#webpack-exodus`

**Comment by yairmelamed** [comment]
Yes.. it works.. but it doesn't save the .web_auth folder.. so I need to scan again.. beside, the official version of whatsapp-web.js is for 2.4.. not 2.3..

**Comment by MOHDaazam** [comment]
@yairmelamed

In my case it saves these two folders
[image: image.png]

and on restarting the services, it says connecting on QR code but it takes
previous authenticated users.

**Comment by MOHDaazam** [comment]
![image](https://github.com/wppconnect-team/wa-version/assets/47951474/8a30ceeb-503d-4de0-98bc-62df7014da99)

**Comment by palbano30** [comment]
Estou com o mesmo problema @mrameen, node-red

**Comment by rizkihermansyah83** [comment]
> ![image](https://private-user-images.githubusercontent.com/47951474/344960801-8a30ceeb-503d-4de0-98bc-62df7014da99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTczODYsIm5iZiI6MTcxOTkxNzA4NiwicGF0aCI6Ii80Nzk1MTQ3NC8zNDQ5NjA4MDEtOGEzMGNlZWItNTAzZC00ZGUwLTk4YmMtNjJkZjcwMTRkYTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDEwNDQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NzYzY2ZiZGZlMzJiMmU5Y2ZkMGViNWJmZDNmM2Q5NmU5NzJkYzJlZmU5OTEyMGVhOGExMWI4NWI4YzAzZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GS_njbo_YWfXGUbmftoOCgW30ZKsVariPETmutojuKk)

it different from node red.. if i do that.. qr code not show and error happen..

**Comment by MOHDaazam** [comment]
In this version of release, no need set these

webVersionCache: {
> type: 'remote',
> remotePath: '
> https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.3000.1014610951-alpha.html
> '
> },


Mine :
const createSession = function (id, description) {
  console.log("Creating session: " + id);
  const client = new Client({
    // restartOnAuthFail: true,
    puppeteer: {
      headless: true,
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage",
        "--disable-web-security",
        "--disable-gpu",
        "--hide-scrollbars",
        "--disable-cache",
        "--disable-application-cache",
        "--disable-gpu-driver-bug-workarounds",
        "--disable-accelerated-2d-canvas",
        "--no-first-run",
        "--no-zygote",
        "--single-process", // <- this one doesn't works in Windows
      ],
    },
    authStrategy: new LocalAuth({
      clientId: id,
      dataPath: './wweb_auth'
    }),

>   });

**Comment by rizkihermansyah83** [comment]
try this.. it working for me.. thankyou.. maturnuwon sanget gays.....
https://github.com/pedroslopez/whatsapp-web.js/issues/2789#issuecomment-2034333596

**Comment by WichyAlonzo** [comment]
client = new Client({
        authStrategy: new LocalAuth(),
        puppeteer: {
            executablePath: 'C:/Program Files/Google/Chrome/Application/chromex.exe',
            headless: false,
            args: ['--no-sandbox', '--disable-setuid-sandbox'],
        },
        webVersionCache: {
            type: 'remote',
            // remotePath: 'https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.2413.51-beta.html',
            remotePath: 'https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.3000.1014590669-alpha',
        }
    });

npm install github:pedroslopez/whatsapp-web.js#webpack-exodus

Done!

**Comment by WichyAlonzo** [comment]
![image](https://github.com/wppconnect-team/wa-version/assets/67400844/711b1a69-b96e-487e-99dc-b1abbe31aca

> ```
> client = new Client({
>     authStrategy: new LocalAuth(),
>     puppeteer: {
>         executablePath: 'C:/Program Files/Google/Chrome/Application/chromex.exe',
>         headless: false,
>         args: ['--no-sandbox', '--disable-setuid-sandbox'],
>     },
>     webVersionCache: {
>         type: 'remote',
>         // remotePath: 'https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.2413.51-beta.html',
>         remotePath: 'https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.3000.1014590669-alpha',
>     }
> });
> ```
> 
> npm install github:pedroslopez/whatsapp-web.js#webpack-exodus
> 
> ¡Hecho!

**Comment by WichyAlonzo** [comment]
![image](https://github.com/wppconnect-team/wa-version/assets/67400844/bbff80f6-1c5b-4866-9254-f2de2a4094bb)

**Comment by manfe** [comment]
I am closing this issue, since it's old issue. I will try to keep it update for next issues.
